# Generated by Django 5.2.4 on 2025-07-26 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_eliminated', models.BooleanField(blank=True, default=False, null=True)),
                ('date_eliminated', models.DateTimeField(blank=True, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('chat_par_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_participant', to='chats.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.CharField(max_length=500)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(blank=True, default=False, null=True)),
                ('is_eliminated', models.BooleanField(blank=True, default=False, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_chat', to='chats.chat')),
                ('user_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.TextField()),
                ('file_type', models.TextField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_attachments', to='chats.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageState',
            fields=[
                ('message_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('last_body', models.CharField(blank=True, editable=False, max_length=500, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_states', to='chats.message')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states_message', to='chats.state')),
            ],
        ),
    ]
