# Generated by Django 5.2.4 on 2025-07-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatparticipant',
            table='chat_participants',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
        migrations.AlterModelTable(
            name='messageattachment',
            table='messages_attachments',
        ),
        migrations.AlterModelTable(
            name='messagestate',
            table='messages_states',
        ),
        migrations.AlterModelTable(
            name='state',
            table='states_messages',
        ),
    ]
