# Generated by Django 5.2.4 on 2025-08-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chatparticipant_table_alter_message_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
